<?php
    function getCities() {
        return [
            "Aba",
            "Abakaliki",
            "Abeokuta",
            "Abuja",
            "Ado Ekiti",
            "Akpawfu",
            "Akure",
            "Asaba",
            "Awka",
            "Bauchi",
            "Benin",
            "Birnin Kebbi",
            "Buguma",
            "Calabar",
            "Dutse",
            "Eket",
            "Enugu",
            "Gombe",
            "Gusau",
            "Ibadan",
            "Ifelodun",
            "Ife",
            "Ikeja",
            "Ikirun",
            "Ikot-Abasi",
            "Ikot Ekpene",
            "Ilorin",
            "Iragbiji",
            "Jalingo",
            "Jimeta",
            "Jos",
            "Kaduna",
            "Kano",
            "Katsina",
            "Karu",
            "Kumariya",
            "Lafia",
            "Lagos",
            "Lekki",
            "Lokoja",
            "Maiduguri",
            "Makurdi",
            "Minna",
            "Nsukka",
            "Offa",
            "Ogbomoso",
            "Onitsha",
            "Okene",
            "Ogaminana",
            "Omu-Aran",
            "Oron",
            "Oshogbo",
            "Owerri",
            "Owo",
            "Orlu",
            "Oyo",
            "Port Harcourt",
            "Potiskum",
            "Sokoto",
            "Suleja",
            "Umuahia",
            "Uyo",
            "Warri",
            "Wukari",
            "Yenagoa",
            "Yola",
            "Zaria",
        ];
    }

function getStates() {
    return [
        "ABIA",
        "ADAMAWA",
        "AKWA IBOM",
        "ANAMBRA",
        "BAUCHI",
        "BAYELSA",
        "BENUE",
        "BORNO",
        "CROSS RIVER",
        "DELTA",
        "EBONYI",
        "EDO",
        "EKITI",
        "ENUGU",
        "GOMBE",
        "IMO",
        "JIGAWA",
        "KADUNA",
        "KANO",
        "KATSINA",
        "KEBBI",
        "KOGI",
        "KWARA",
        "LAGOS",
        "NASSARAWA",
        "NIGER",
        "OGUN",
        "ONDO",
        "OSUN",
        "OYO",
        "PLATEAU",
        "RIVERS",
        "SOKOTO",
        "TARABA",
        "YOBE",
        "ZAMFARA",
    ];
}